import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Rumble Court',
  description: 'AI-Driven Courtroom Simulator',
=======
  title: 'The Urim',
  description: 'Generated by create next app',
>>>>>>> origin/main
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): React.JSX.Element {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}