/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RumbleCourt {
  export type CaseStruct = {
    caseId: BigNumberish;
    plaintiff: AddressLike;
    caseTitle: string;
    evidenceHash: string;
    filedAt: BigNumberish;
    status: BigNumberish;
  };

  export type CaseStructOutput = [
    caseId: bigint,
    plaintiff: string,
    caseTitle: string,
    evidenceHash: string,
    filedAt: bigint,
    status: bigint
  ] & {
    caseId: bigint;
    plaintiff: string;
    caseTitle: string;
    evidenceHash: string;
    filedAt: bigint;
    status: bigint;
  };

  export type VerdictStruct = {
    caseId: BigNumberish;
    verdictType: BigNumberish;
    reasoning: string;
    timestamp: BigNumberish;
    isFinal: boolean;
  };

  export type VerdictStructOutput = [
    caseId: bigint,
    verdictType: bigint,
    reasoning: string,
    timestamp: bigint,
    isFinal: boolean
  ] & {
    caseId: bigint;
    verdictType: bigint;
    reasoning: string;
    timestamp: bigint;
    isFinal: boolean;
  };
}

export interface RumbleCourtInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "appealCase"
      | "cases"
      | "fileCase"
      | "getCase"
      | "getTotalCases"
      | "getUserCases"
      | "getVerdict"
      | "hasVerdict"
      | "nextCaseId"
      | "owner"
      | "recordVerdict"
      | "startTrial"
      | "userCases"
      | "verdicts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CaseAppealed"
      | "CaseFiled"
      | "TrialStarted"
      | "VerdictRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "appealCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cases", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fileCase",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCases",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerdict",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVerdict",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCaseId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordVerdict",
    values: [BigNumberish, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "startTrial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userCases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verdicts",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "appealCase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cases", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fileCase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVerdict", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVerdict", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextCaseId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTrial", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userCases", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verdicts", data: BytesLike): Result;
}

export namespace CaseAppealedEvent {
  export type InputTuple = [caseId: BigNumberish];
  export type OutputTuple = [caseId: bigint];
  export interface OutputObject {
    caseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseFiledEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    plaintiff: AddressLike,
    caseTitle: string
  ];
  export type OutputTuple = [
    caseId: bigint,
    plaintiff: string,
    caseTitle: string
  ];
  export interface OutputObject {
    caseId: bigint;
    plaintiff: string;
    caseTitle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrialStartedEvent {
  export type InputTuple = [caseId: BigNumberish];
  export type OutputTuple = [caseId: bigint];
  export interface OutputObject {
    caseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictRecordedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    verdictType: BigNumberish,
    isFinal: boolean
  ];
  export type OutputTuple = [
    caseId: bigint,
    verdictType: bigint,
    isFinal: boolean
  ];
  export interface OutputObject {
    caseId: bigint;
    verdictType: bigint;
    isFinal: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RumbleCourt extends BaseContract {
  connect(runner?: ContractRunner | null): RumbleCourt;
  waitForDeployment(): Promise<this>;

  interface: RumbleCourtInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  appealCase: TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;

  cases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint] & {
        caseId: bigint;
        plaintiff: string;
        caseTitle: string;
        evidenceHash: string;
        filedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  fileCase: TypedContractMethod<
    [caseTitle: string, evidenceHash: string],
    [bigint],
    "nonpayable"
  >;

  getCase: TypedContractMethod<
    [caseId: BigNumberish],
    [RumbleCourt.CaseStructOutput],
    "view"
  >;

  getTotalCases: TypedContractMethod<[], [bigint], "view">;

  getUserCases: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getVerdict: TypedContractMethod<
    [caseId: BigNumberish],
    [RumbleCourt.VerdictStructOutput],
    "view"
  >;

  hasVerdict: TypedContractMethod<[caseId: BigNumberish], [boolean], "view">;

  nextCaseId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordVerdict: TypedContractMethod<
    [
      caseId: BigNumberish,
      verdictType: BigNumberish,
      reasoning: string,
      isFinal: boolean
    ],
    [void],
    "nonpayable"
  >;

  startTrial: TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;

  userCases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  verdicts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, boolean] & {
        caseId: bigint;
        verdictType: bigint;
        reasoning: string;
        timestamp: bigint;
        isFinal: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "appealCase"
  ): TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint] & {
        caseId: bigint;
        plaintiff: string;
        caseTitle: string;
        evidenceHash: string;
        filedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fileCase"
  ): TypedContractMethod<
    [caseTitle: string, evidenceHash: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCase"
  ): TypedContractMethod<
    [caseId: BigNumberish],
    [RumbleCourt.CaseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalCases"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCases"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVerdict"
  ): TypedContractMethod<
    [caseId: BigNumberish],
    [RumbleCourt.VerdictStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVerdict"
  ): TypedContractMethod<[caseId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextCaseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordVerdict"
  ): TypedContractMethod<
    [
      caseId: BigNumberish,
      verdictType: BigNumberish,
      reasoning: string,
      isFinal: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startTrial"
  ): TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verdicts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, boolean] & {
        caseId: bigint;
        verdictType: bigint;
        reasoning: string;
        timestamp: bigint;
        isFinal: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CaseAppealed"
  ): TypedContractEvent<
    CaseAppealedEvent.InputTuple,
    CaseAppealedEvent.OutputTuple,
    CaseAppealedEvent.OutputObject
  >;
  getEvent(
    key: "CaseFiled"
  ): TypedContractEvent<
    CaseFiledEvent.InputTuple,
    CaseFiledEvent.OutputTuple,
    CaseFiledEvent.OutputObject
  >;
  getEvent(
    key: "TrialStarted"
  ): TypedContractEvent<
    TrialStartedEvent.InputTuple,
    TrialStartedEvent.OutputTuple,
    TrialStartedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictRecorded"
  ): TypedContractEvent<
    VerdictRecordedEvent.InputTuple,
    VerdictRecordedEvent.OutputTuple,
    VerdictRecordedEvent.OutputObject
  >;

  filters: {
    "CaseAppealed(uint256)": TypedContractEvent<
      CaseAppealedEvent.InputTuple,
      CaseAppealedEvent.OutputTuple,
      CaseAppealedEvent.OutputObject
    >;
    CaseAppealed: TypedContractEvent<
      CaseAppealedEvent.InputTuple,
      CaseAppealedEvent.OutputTuple,
      CaseAppealedEvent.OutputObject
    >;

    "CaseFiled(uint256,address,string)": TypedContractEvent<
      CaseFiledEvent.InputTuple,
      CaseFiledEvent.OutputTuple,
      CaseFiledEvent.OutputObject
    >;
    CaseFiled: TypedContractEvent<
      CaseFiledEvent.InputTuple,
      CaseFiledEvent.OutputTuple,
      CaseFiledEvent.OutputObject
    >;

    "TrialStarted(uint256)": TypedContractEvent<
      TrialStartedEvent.InputTuple,
      TrialStartedEvent.OutputTuple,
      TrialStartedEvent.OutputObject
    >;
    TrialStarted: TypedContractEvent<
      TrialStartedEvent.InputTuple,
      TrialStartedEvent.OutputTuple,
      TrialStartedEvent.OutputObject
    >;

    "VerdictRecorded(uint256,uint8,bool)": TypedContractEvent<
      VerdictRecordedEvent.InputTuple,
      VerdictRecordedEvent.OutputTuple,
      VerdictRecordedEvent.OutputObject
    >;
    VerdictRecorded: TypedContractEvent<
      VerdictRecordedEvent.InputTuple,
      VerdictRecordedEvent.OutputTuple,
      VerdictRecordedEvent.OutputObject
    >;
  };
}
